services:
  - type: web
    name: edubot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Edubot:app
    pythonVersion: 3.10.13
    autoDeploy: true
